import React from "react";

interface FileNode {
  name: string;
  type: "file" | "directory";
  children?: FileNode[];
  path?: string;
}

interface FileStructureViewerProps {
  structure: FileNode[];
  onFileSelect?: (filePath: string) => void;
}

export function FileStructureViewer({
  structure,
  onFileSelect,
}: FileStructureViewerProps) {
  const renderNode = (node: FileNode, depth: number = 0) => {
    const paddingLeft = depth * 20;

    if (node.type === "directory") {
      return (
        <div key={node.name}>
          <div
            className="flex items-center py-1 px-2 hover:bg-gray-100 rounded cursor-pointer"
            style={{ paddingLeft }}
          >
            <span className="text-gray-600 mr-2">📁</span>
            <span className="font-medium text-gray-900">{node.name}</span>
          </div>
          {node.children && (
            <div>
              {node.children.map((child) => renderNode(child, depth + 1))}
            </div>
          )}
        </div>
      );
    } else {
      return (
        <div
          key={node.name}
          className="flex items-center py-1 px-2 hover:bg-gray-100 rounded cursor-pointer"
          style={{ paddingLeft }}
          onClick={() => node.path && onFileSelect?.(node.path)}
        >
          <span className="text-gray-600 mr-2">📄</span>
          <span className="text-gray-700">{node.name}</span>
        </div>
      );
    }
  };

  return (
    <div className="bg-white rounded-lg shadow-md border border-gray-200 p-4">
      <h3 className="font-semibold text-gray-900 mb-3">Project Structure</h3>
      <div className="bg-gray-50 rounded-lg p-3">
        {structure.map((node) => renderNode(node))}
      </div>
      <div className="mt-3 text-xs text-gray-500">
        Note: This is a visualization of the project structure. Files are
        generated by the agent system.
      </div>
    </div>
  );
}

export function generateSampleStructure(appName: string): FileNode[] {
  return [
    {
      name: "src/",
      type: "directory",
      children: [
        {
          name: "app/",
          type: "directory",
          children: [
            { name: "globals.css", type: "file", path: "src/app/globals.css" },
            { name: "layout.tsx", type: "file", path: "src/app/layout.tsx" },
            { name: "page.tsx", type: "file", path: "src/app/page.tsx" },
          ],
        },
        {
          name: "components/",
          type: "directory",
          children: [
            {
              name: "AgenticComposer.tsx",
              type: "file",
              path: "src/components/AgenticComposer.tsx",
            },
            {
              name: "ComponentPreview.tsx",
              type: "file",
              path: "src/components/ComponentPreview.tsx",
            },
            {
              name: "FileStructureViewer.tsx",
              type: "file",
              path: "src/components/FileStructureViewer.tsx",
            },
          ],
        },
        {
          name: "lib/",
          type: "directory",
          children: [
            {
              name: "agent-orchestrator.ts",
              type: "file",
              path: "src/lib/agent-orchestrator.ts",
            },
            {
              name: "mcp-tools.ts",
              type: "file",
              path: "src/lib/mcp-tools.ts",
            },
          ],
        },
        {
          name: "types/",
          type: "directory",
          children: [
            { name: "index.ts", type: "file", path: "src/types/index.ts" },
          ],
        },
      ],
    },
    { name: "package.json", type: "file", path: "package.json" },
    { name: "tsconfig.json", type: "file", path: "tsconfig.json" },
    { name: "README.md", type: "file", path: "README.md" },
  ];
}
